version: '3.0'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
  web:
    image: philaguy/infra_web
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ./fixtures.json:/app/fixtures.json 
    depends_on:
      - db
    env_file:
      - ../.env 
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./static/redoc.yaml:/var/html/redoc/redoc.yaml
      - ./template/redoc.html:/var/html/redoc/redoc.html
    depends_on:
      - web

volumes:
  static_value:
  media_value:
